apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  labels:
    app: user
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user
  template:
    metadata:
      labels:
        app: user
      annotations:
        linkerd.io/inject: enabled
        config.linkerd.io/proxy-cpu-request: 1m
        config.linkerd.io/proxy-memory-request: 7Mi
    spec:
      imagePullSecrets:
        - name: ghcr
      containers:
        - name: user
          image: busybox
          command:
            - /app/servicebin
          livenessProbe:
            exec:
              command:
                - /app/grpc_health_probe
                - -addr=:8080
          readinessProbe:
            exec:
              command:
                - /app/grpc_health_probe
                - -addr=:8080
          ports:
            - containerPort: 8080
              name: grpc
              protocol: TCP
          resources:
            requests:
              cpu: 5m
              memory: 47Mi
            limits:
              cpu: "1"
              memory: 1Gi
          env:
            - name: GRPC_PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: grpc
            - name: MONGODB_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: mongodb
            - name: HOST_URL
              valueFrom:
                configMapKeyRef:
                  key: url
                  name: host
            - name: VK_APPID
              valueFrom:
                configMapKeyRef:
                  key: appid
                  name: vk
            - name: VK_APPSECRETKEY
              valueFrom:
                secretKeyRef:
                  key: appsecretkey
                  name: vk
            - name: YANDEX_APPID
              valueFrom:
                configMapKeyRef:
                  key: appid
                  name: yandex
            - name: YANDEX_APPPASSWORD
              valueFrom:
                secretKeyRef:
                  key: apppassword
                  name: yandex
            - name: SERVICE_PARSER
              valueFrom:
                configMapKeyRef:
                  key: parser
                  name: service
            - name: LOGLEVEL
              value: error

---
apiVersion: v1
kind: Service
metadata:
  name: user
  labels:
    app: user
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: user
